### ISSUE TITLE
Is there a way to configure to not create AssemblyFileVersionAttribute

### ISSUE THREAD

**Issue by neilsilver** [dotnet/Nerdbank.GitVersioning#1025]
Im trying to apply to a .net framework 3.5 project and all works well.

However the nuget Generates an AssemblyFileVersionAttribute which is not supported in .net 3.5.

Ive searched the issues and docs but i can find a way to configure to not create this ?

`[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.0.1.0")]`

**Comment by AArnott** [comment]
> AssemblyFileVersionAttribute which is not supported in .net 3.5.

There must be some mistake. That attribute has been supported since .NET Framework 1.0, as documented here:
https://apisof.net/catalog/8450123a-1629-71ba-af60-76e63189fe24

Can you share a repro project and the actual error message?

**Comment by neilsilver** [comment]
Thanks @AArnott   it might .. of course be related to the sandboxed environment im working in.

![image](https://github.com/dotnet/Nerdbank.GitVersioning/assets/19469812/eb4347af-abc9-4074-905d-bd34bdceae75)

In my assembly Explorer its not there but in for example 4.7.2. it is.

**Comment by AArnott** [comment]
Are you perhaps targeting the .NET *Micro* or *Compact* Framework instead of .NET Framework?
What is the file path to the assembly that is missing this attribute? If it's actually a standard .NET Framework path, I suspect corruption of some kind.

Anyway, you can workaround it by turning the assembly version file generation off. There's an msbuild property to do that: set `GenerateAssemblyVersionInfo` to `false`.

**Comment by neilsilver** [comment]
Yes the targeting is CF my bad ! 

Ill look into your workaround many thanks.
