### ISSUE TITLE
PrivateP2PCaching.proj' could not be found

### ISSUE THREAD

**Issue by bkblie** [dotnet/Nerdbank.GitVersioning#1030]
Getting this in my build log
The referenced component 'c:\code\myproject\packages\Nerdbank.GitVersioning.3.6.133\build\PrivateP2PCaching.proj' could not be found.

Is there a fix for this?

**Comment by bkblie** [comment]
Removed all refrences to Nerdbank.GitVersioning from solution
Deleted my local nuget cache in my profile and solution packages directory
Added the Nerdbank.GitVersioning Nuget to one project in my solution and get this error once more.
![image](https://github.com/dotnet/Nerdbank.GitVersioning/assets/20906284/e6b662d1-6be5-4e36-aea4-302ed9a96e03)

**Comment by bkblie** [comment]
Looks like this, not sure, https://github.com/dotnet/Nerdbank.GitVersioning/issues/787

**Comment by AArnott** [comment]
That additional context totally changes how I interpret your original report. I thought you were reporting a build failure, but I now see you're just reporting a Visual Studio UI glyph.
That's just Visual Studio misinterpreting an msbuild item. I _think_ I've already done all I can to minimize those issues. You should probably use Report a Problem in VS to get the project system to stop reporting that, since NB.GV isn't doing anything wrong here.

Alternatively, upgrade your projects to SDK style, which switches you to a newer project system in VS that doesn't complain about this.
