### ISSUE TITLE
Support using tags as only source for version

### ISSUE THREAD

**Issue by mortenn** [dotnet/Nerdbank.GitVersioning#1041]
Thanks for your efforts thus far!

It would be great if I could use this tool in pipelines without needing to add additional artifacts to the tree.

To this end, I would like to see the tool read tags in the tree, and combine that with "git height" to spit out a version number.

Say the commit is tagged v1.0.0; version should then simply be 1.0.0  
Another commit is made, the version would then become 1.0.1

Cheers, Morten

**Comment by AArnott** [comment]
That would lead to one commit building as one version one day, and as another version another day, merely due to the addition of a tag to the repo. That runs counter to the NB.GV philosophy, which is that a given commit only produces one (or two, due to the PublicRelease flag) version. 

But there is a community out there that wants what you're asking for. I suggest they use [GitVersion](https://github.com/GitTools/GitVersion?tab=readme-ov-file#readme), which uses branch names, tag names, and PR environment variables to compute the version.
