### ISSUE TITLE
Question about deleted version.json files apparently still having an effect

### ISSUE THREAD

**Issue by mackie1001** [dotnet/Nerdbank.GitVersioning#1066]
We've decided to pivot away from separately versioned assemblies and executables in our .Net 8 project and control it all at the top level. As a result a new top level version.json was created and directory/project specific ones deleted. However if I run `nbgv get-version` in the directories that used to have their own version.json I still see a different version number vs when I run it inside the top level `src` directory. 

Is it looking in the history for previous version.json files and is this expected behaviour? If so, Is it something we can control?

**Comment by AArnott** [comment]
Yes, this is expected. NB.GV works very hard to avoid any project accidentally versioning _backwards_. While a project had its own version.json file set to 1.0, it was versioning with every commit, and might have been at 1.0.123 at some point. Then you delete that version.json file but the root directory in the repo still has "1.0" set as the version. You wouldn't want your leaf project to reset to 1.0.1 at that point. So NB.GV sees through these evolutions in your project and versions the leaf project at 1.0.124. 

There are two ways forward: 

1. Accept what you're getting for now. When you next bump the version (e.g. change the root to 1.1), all projects will follow and match from that point going forward.
2. Take the heavier step of [creating a commit in which _no_ version.json file exists](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/migrating.md) and then reintroduce them. This will reset version height to '1' everywhere. But you take on your own responsibility for backward versioning. You could then 'fix' the backwardness by artificially inflating the version height by adding `"versionHeightOffset": 123` to the root version.json file, so that _all_ the repo builds 1.0.124 instead of 1.0.1 to avoid going backwards and still get the whole repo onto the same version number.

**Comment by mackie1001** [comment]
Sorry for the late reply. Thanks for the response, the reasoning makes perfect sense.

To reiterate,  if we bump the major.minor in the root version.json it'll know there's no chance of a lower version number and happily only use the top level config?

**Comment by AArnott** [comment]
Yes, if I'm understanding your question correctly.
And you can always test it by making a local commit with your changes and building (or running the `nbgv` tool).
