### ISSUE TITLE
Update-Release - Deleting Most of version.json

### ISSUE THREAD

**Issue by msteel9999** [dotnet/Nerdbank.GitVersioning#1079]
Please see the attached before and after files.

[BEFORE_version.json](https://github.com/user-attachments/files/16625660/BEFORE_version.json)
[AFTER_version.json](https://github.com/user-attachments/files/16625658/AFTER_version.json)

Powershell input is as follows:
nbgv prepare-release

where I am in a folder one level down from repository root and contains a file version.json (see BEFORE_version.json above)

Powershell output is as follows:

release/1.2.0 branch now tracks v1.2.0 stabilization and release.
<branch name> branch now tracks v1.3.0-alpha development.

**Comment by AArnott** [comment]
Is your report that several properties were removed from the file unexpectedly?

**Comment by AArnott** [comment]
The only unexpected parts of this diff are:

```diff
5c5
<     "^refs/heads/release-private/\\d+\\.\\d+\\.?\\d*"
>     "^refs/heads/release/\\d+\\.\\d+\\.?\\d*"
14,16c8
<     "branchName": "release-private/{version}",
>     "branchName": "release/{version}"
```

And this is the one part I cannot repro with the latest nbgv version. Are you sure the nbgv tool made this change? I can't imagine why it would have done that. I wonder if you introduced that change yourself.

The rest of the removals are because they are defaults, and anytime nbgv writes the version file, it omits defaults. I don't know how to avoid that while also preventing it from _adding_ a bunch of other properties that are left at their defaults.

**Comment by msteel9999** [comment]
I am testing using the clone latest version.

I would expect the existing values to remain after preparing a release and
the version to be incremented.

I haven't made any changes myself yet so this is how it works.

Why would I want to specify every option every time I use it. I want to
configure my version settings once.

I will submit a PR if I ever get anywhere with it maybe introduce an option
or something.

Thanks


Martin Steel
Barnett Waddingham

**Comment by AArnott** [comment]
I still don't understand what your complaint is regarding. The _dropped_ properties are dropped because they are setting values to what is their default anyway. 
The _changed_ properties (the branch name patterns) would be a bug, but I can't repro it. If you can provide a repro for it (maybe access to your repo or a minimal one you create), then I'm happy to investigate.

As I said, I don't know of a way to "fix" the removal of properties that are already at their defaults. 

> Why would I want to specify every option every time I use it. I want to
configure my version settings once.

I don't understand this. How/where are you specifying options every time you use it? If you're talking about the options that are disappearing from version.json, you don't need to put those back, since they are equivalent whether they are missing or set to their defaults as you have them.

**Comment by msteel9999** [comment]
I see what you're saying. It's not technically doing anything wrong it's just  bit odd.

I've never seen this happening in any other program but if it's only defaults I agree it doesn't matter.
