### ISSUE TITLE
Option to disable the two-byte build number

### ISSUE THREAD

**Issue by filipnavara** [dotnet/Nerdbank.GitVersioning#444]
Is there any way to disable the generation of build number from the two bytes of the GIT commit hash?

**Comment by AArnott** [comment]
Yes, but what exactly are you trying to remove it from? The package version? The AssemblyFileVersion?

**Comment by filipnavara** [comment]
AssemblyFileVersion in our case.

**Comment by AArnott** [comment]
AssemblyFileVersion doesn't have any functional impact on anyone (that I know of). Leveraging the last integer for the first two bytes of the commit hash remove the ambiguity that you might have from just the major.minor.height version so that you can always tie the assembly file version back to the exact commit id.
Why do you want to suppress that?

**Comment by filipnavara** [comment]
That's tricky to answer.

We need a three-component version number to fit our (legacy) distribution system. Our original versioning used SVN where major.minor was fixed based on a product version branch and build number was set to SVN revision (ie. monotonically increasing counter). Revision was set to zero for official builds and non-zero for locally modified builds.

We migrated the versioning system to GIT and started using NerdBank.GitVersioning as the tool for generating the version information. This works great in general but we still need a version number that fits the major.minor.build.0 for official builds that interact with the installation and version tracking infrastructure. Unfortunately there's no such number available directly:

- `AssemblyInformationalVersion` uses textual version that is unsuitable for places where `System.Version` class is used for comparison
- `AssemblyVersion` contains just the major.minor version and not the GIT height
- `AssemblyFileVersion` has non-zero revision number

Of course we can introduce some helper method to get stripped-down `AssemblyFileVersion` but we tried to avoid it as we access the version information from many places across different assemblies and replacing the logic is potentially error prone.

**Comment by AArnott** [comment]
So it sounds like you can decide which attribute to get the version info from. Is that right?

You can change version.json so that `AssemblyVersion` will have the 3-integer value. That's not the default because if folks compile against 1.2.3 and run against 1.2.4, they'll need binding redirects on .NET Framework. If that's not an issue for you though, then simply increasing the precision of the AssemblyVersion is the easiest route for you.

Otherwise, you can override the AssemblyFileVersion by adding msbuild authoring like this:

```xml
<Target Name="Use3DigitFileVersion" AfterTargets="GetBuildVersion">
  <PropertyGroup>
    <AssemblyFileVersion>$(BuildVersionSimple)</AssemblyFileVersion>
  </PropertyGroup>
</Target>
```

**Comment by filipnavara** [comment]
Thanks for the tips, I will give it a try. I do have some control over which version property to use but some parts of code read it from the native FILEVERSIONINFO resource and I'll have to audit those.
