### ISSUE TITLE
nbgv install throws an unhandled exception and fails to output details of it

### ISSUE THREAD

**Issue by vcaraulean** [dotnet/Nerdbank.GitVersioning#450]
I'm trying to follow the guide on setting up versioning. After installing the tool, running install results in this:

```
C:\Dev\Server [feature/versioning]> nbgv install

Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.
```

Version: `nbgv v3.1.68+g68f1376ada`

After running, a `version.json` file is created. But no changes are added to my existing `Directory.Build.props` file, as mentioned in the install docs.

**Comment by vcaraulean** [comment]
Well, found 2 interesting things:
 - Searched for that exception and, apparently, it's coming from `coreclr`
 - When the error happened, I was off of the corp's VPN. When I got back there and re-ran the program, it correctly carried modifications to `Directory.Build.props`. It failed probably because network access to without VPN is restricted.

Oh, and 3rd find: when building solution, it fails on few projects, _randomly_:
```
C:\Users\v951592\.nuget\packages\nerdbank.gitversioning\3.1.68\build\Nerdbank.GitVersioning.targets(71,5): error MSB4062: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task could not be loaded from the assembly C:\Users\v951592\.nuget\packages\nerdbank.gitversioning\3.1.68\build\MSBuildCore/Nerdbank.GitVersioning.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 
```

**Comment by AArnott** [comment]
nbgv itself doesn't have any VPN dependency. Are the files it was trying to read or change accessible only over VPN? If so, that would make sense.
It's disappointing that coreclr can't print the exception though. Do I understand correctly that coreclr is responsible for that failure, or could you tell that nbgv itself had code whose Exception.ToString() threw an exception?

Your 3rd find issue isn't supposed to happen, but it may be due to you reusing the same build processes across multiple NB.GV versions. To fix this, make sure you're using the same version of NB.GV throughout your repo. Then before trying to build the repo (after switching from another one or after a NB.GV upgrade) use either `msbuild /nr:false your-solution` or ` dotnet build-server shutdown` followed by your `dotnet build` command.

**Comment by vcaraulean** [comment]
I've looked through nbgv's code and there are no exceptions defined (apparently). Googling the string revealed similar reports in `coreclr` repo, so, I think, it' not nbgv's fault.

Regarding my 3rd issue, your suggestion to run "shutdown" worked. I've ran nbgv from IDE then from cmd line, as a tool. 

Thanks for your help!
