### ISSUE TITLE
Version of the build for pull request seems incorrect or what am I doing wrong?

### ISSUE THREAD

**Issue by mpazdnikova** [dotnet/Nerdbank.GitVersioning#459]
Hi,

I've just set up versioning for my project. Here is version.json:
```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.0",
  "cloudBuild": {
    "setVersionVariables": true,
    "buildNumber": {
      "enabled": true,
      "includeCommitId": {
        "when": "nonPublicReleaseOnly",
        "where": "buildMetadata"
      }
    }
  },
  "nugetPackageVersion": {
    "semVer": 2
  },
  "publicReleaseRefSpec": [
    "^refs/heads/master$"
  ]
}
```
I have a build pipeline established which calls `nbgv cloud`. The policy for master branch requires the build for pull request to pass.

And here what I see in builds:
![image](https://user-images.githubusercontent.com/19838305/78032991-80a33d80-736e-11ea-97ba-8975b9db1a13.png)

I have 0.0.8 and 0.0.9 which are built from master and are perfectly fine. However, builds made for pull requests have upper versions up to 0.0.12-smth now. I would expect them to have the version of the current master build + some suffix. How to accomplish that?

Sorry if that's a total noob question, I'm just getting started :)

**Comment by AArnott** [comment]
No problem. :)

It's evident that PR 11064 was *squashed* on completion, since the height of the PR build was 9 and the height of the CI that merged it was also 9. If you had *merged* it, the CI build would have had a height of 10 (= the PR build +1 for the merge commit). Squashing is fine, but you should know that that will always result in a height of "last CI + 1" instead of "last PR build + 1".

>  I would expect them to have the version of the current master build + some suffix

It sounds like your expectations aren't quite aligned with the functionality. `master` doesn't set the version height. The version height is a calculation from HEAD to the point where your `major.minor` version was last set. So each commit that your PR introduces adds one to the 'version height' which makes up the 3rd integer in the version. 

Does that help?
