### ISSUE TITLE
Subtle difference in AssemblyFileVersion between version 2 and 3

### ISSUE THREAD

**Issue by azeno** [dotnet/Nerdbank.GitVersioning#477]
When switching from version 2 to version 3 of this library I noticed a subtle (but breaking) difference in the way the AssemblyFileVersion property is calculated.

I am using `2020.1.0-{height}` as a version scheme, which lead to the following variables in version 2:

`Version:                      2020.1.0.1`
`AssemblyFileVersion:              2020.1.0.1`
`AssemblyVersion:              2020.1.0.0`
`AssemblyInformationalVersion: 2020.1.0-1+c643598734`
`NuGet package Version:        2020.1.0-0001-gc643598734`

while in version 3 I get:

`Version:                      2020.1.0`
`AssemblyFileVersion:              2020.1.0.0`
`AssemblyVersion:              2020.1.0.0`
`AssemblyInformationalVersion: 2020.1.0-1+c643598734`
`NuGet package Version:        2020.1.0-0001-gc643598734`

Notice the subtle difference of the revision being zero in `AssemblyFileVersion` while it was set to the git version height before.
Is there a particular reason for this different behavior?

**Comment by AArnott** [comment]
I think this behavioral difference is what I called out in the [3.0 release notes](https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.0.24).

If adding another commit does in fact bump the 4th integer of `AssemblyFileVersion`, then it certainly sounds like that documented change. But if `AssemblyFileVersion` simply no longer ever shows version height when `{height}` is moved out of the version, that should have been documented.

**Comment by azeno** [comment]
Hm, making more commits or setting `versionHeightOffset` greater zero, I don't get the old behavior back. The revision of `AssemblyFileVersion` is always zero. In other words in order to get the revision in my application I'd need to manually parse the `AssemblyInformationalVersion` attribute.

I only see the revision increasing if I replace `-{height}` with `-preview` as the pre-release tag and let the system append `.{height}` to the version. But doing so one loses those nicely ordered NuGet package versions.

If that is indeed the intended behavior I'll shut up and stick to version 2 I guess.

**Comment by AArnott** [comment]
I can't remember for sure how 'by design' this change was then. But I guess we can argue that when you move `{height}` out of the 4-integer version as you've done in version.json, you don't want it in the 4-integer version.

>  In other words in order to get the revision in my application I'd need to manually parse the AssemblyInformationalVersion attribute.

Have you checked the `ThisAssembly` class? At least you don't have to use reflection to find the attribute, but you'd still need to parse it out. 

I'm willing to reconsider putting the height back into `AssemblyFileVersion` in the case that you've explicitly moved it *out* using `-{height}` in the version. But it would feel kinda weird to seemingly go against what you asked for there.
