### ISSUE TITLE
Get created release branch from prepare-release as environment variable?

### ISSUE THREAD

**Issue by pergardebrink** [dotnet/Nerdbank.GitVersioning#489]
I am trying to setup a script for creating a release branch with prepare-release which I find really useful!
 
Currently with the latest stable version I need to parse the standard output and find the release branch on the first line to know what branch to push to remote. This has been improved in the latest beta so I can parse it as json at least, but I was wondering if it would be possible to get the branch name as an environment variable or similar? 

If so, it would be super easy to write a script that would do something like this:
```
nbgv prepare-release
git push origin %NBGV_RELEASE_BRANCH%
git push origin master
```

**Comment by AArnott** [comment]
No, that's technically impossible. nbgv is not a .cmd script which runs in the cmd.exe process. If it were, it could set env vars that impact your cmd line environment. But since nbgv is another process, any env vars it sets will not impact its parent (cmd.exe) when it exits.

The alternative that you mention of parsing the json yourself is your only alternative.

FWIW, I find it heaps easier in PowerShell. I suggest you write your scripts in ps1. :)

**Comment by pergardebrink** [comment]
Ah, of course you are right about that and I didn't think about that, my bad! 

I am currently running it from a python script, so it's working fine parsing the text output, and when next version is released (is there any ETA for that?) I'll switch to using json instead, I was just thinking it would be easier to not having to parse anything at all.

Thanks for a great library btw!

**Comment by AArnott** [comment]
There's not an ETA for 3.2 to come out as a stable version. There's very little new in it, and I usually try to pack more stuff into a minor release. But it looks like 3.2.27-beta was supposed to go out to nuget.org but got stuck in the pipeline. I've restarted it. That should unblock you I think, yes?
