### ISSUE TITLE
Public releases and tags

### ISSUE THREAD

**Issue by rioka** [dotnet/Nerdbank.GitVersioning#519]
I've been using NBGV in a very basic way so far, but now I'm trying to take advantage of some more advanced features, so playing with settings to better understand how it works.

So far everything has been quite straight forward, thanks to documentation, expect for a possibly minor issue

Here is what I was trying to achieve

- use `master`
- feature branches from `master` for normal development
- `release/vx.y.z` from `master` before a release
  - tag commit as `vx.y.z` before merging back to `master`

This is my `version.json`

```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.2.1",
  ...
  "publicReleaseRefSpec": [
    "^refs/heads/master$", 
    "^refs/tags/v\\d+\\.\\d+\\.\\d+$" 
  ],
  ...
```

So let's say for example, I have commit `7dc71aea95` in branch `release/v1.2.1`, and this commit is tagged as `v1.2.1`.

If I check out `release/v1.2.1`, or tag `v1.2.1` explicitly, and run `nbgv get-version`, `NugetPackageVersion` is computed as ` 1.2.1-g7dc71aea95`, whereas I'd expect it to be just `1.2.1` instead.

I guess I'm missing something, but cannot figure out what.

Thx

**Comment by AArnott** [comment]
Your `publicReleaseRefSpec` indicates that you'll only get public release versions (e.g. "1.2.1" instead of "1.2.1-g7dc71aea95") when you have the `master` branch checked out, or when building a tag named `v1.2.3` or similar. In git, you can check out a branch but you can't really check out a tag. When you check out a tag, you really just check out a commit behind the tag -- nothing remains to know that you checked out the *tag*. So you don't get public release versions locally when checking out a tag. You only get them when building in a cloud build service that sets env vars to indicate that a _tag_ is being built. 

Since you want public releases in your release branches, you should add another entry to the `publicReleaseRefSpec` array. Perhaps this: `^refs/heads/release/v\\d+\\.\\d+\\.\\d+$` which should get it to produce public releases when you check out those branches.

**Comment by rioka** [comment]
Hi Andrew
> You only get them when building in a cloud build service that sets env vars to indicate that a tag is being built.

Makes sense... when I saw this snippet
```
  "publicReleaseRefSpec": [
    "^refs/heads/master$", // we release out of master
    "^refs/tags/v\\d+\\.\\d+" // we also release tags starting with vN.N
  ],
``` 
in `versionJson.md` I hoped some sort of _magic_ was happening locally...

Actually, manually setting env variables properly did the trick when building locally.
Thanks for helping me understanding how it works.

Kudos
