### ISSUE TITLE
set-env disabled for Github Actions

### ISSUE THREAD

**Issue by kamronbatman** [dotnet/Nerdbank.GitVersioning#535]
Github has disabled `set-env`:
https://github.com/dotnet/Nerdbank.GitVersioning/blob/57a48267cb748f0e1469bd1b346e23932f8cfe9b/azure-pipelines/Set-EnvVars.ps1#L49

So builds that use NBGV for versioning are failing.

More info:
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by AArnott** [comment]
Thanks, @kamronbatman. In fact the symptom you describe that nbgv builds are failing is *not* due to this code location. That symptom is already fixed in #516. If you're still seeing this in your github workflow, make sure you're using the latest version of Nerdbank.GitVersioning and/or the `dotnet/nbgv` github Action.

As *this* repo does not build on GitHub Actions, the code location you call out is not actually impacting anything. It's merely there because this script is shared across many repos. The master location of this script was [updated recently](https://github.com/AArnott/Library.Template/pull/80) so this repo will get an update eventually when I copy over the latest script.

**Comment by kamronbatman** [comment]
Not sure why then but I am having that issue with the newest github actions version. It stopped erroring when I turned off setting the variables in version.json. hmm

**Comment by AArnott** [comment]
@kamronbatman The `version.json` file does not impact behavior of the `dotnet/nbgv` Action as far as setting paths or environment variables. So if changing that file fixed it, you likely have a `Nerdbank.GitVersioning` *package* reference in your repo somewhere that needs to be updated as well.

**Comment by kamronbatman** [comment]
I am referencing it in my csproj, and it is the newest version, 3.3.37. I assumed I needed it for `dotnet/nbgv`?
There is another possibility, but not sure how to investigate, and that is github not pulling the newest action from master.
