### ISSUE TITLE
[Question] nbgv prepare-release

### ISSUE THREAD

**Issue by eddynaka** [dotnet/Nerdbank.GitVersioning#557]
Hi,

I have the following scenario:
- I'm at the main branch
- My current version control is:
```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.3.1-beta.{height}",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/v\\d+(?:\\.\\d+)?$"
  ]
}
```

When I executed the command `nbgv prepare-release` from main, it created three commits in main:
1. Set version to 1.3.1
2. Set Version to 1.4.0-alpha.height
3. Merge

What I thought it would do is: create a new branch so I could push and merge in GitHub. Then, I would trigger the pipeline to generate the new version 1.3.1. After that, another branch would be created, so I could merge the new changes in the version pointing to 1.4.0-alpha.height.

Did I do something wrong?

Thank you!

**Comment by AArnott** [comment]
I expect you may have missed that the command created a `v1.3.1` branch (or similar). It was on that branch that the commit to remove the -beta suffix would be done. Then the main branch was set to 1.4.0-alpha. Finally, since the preceding two commits would produce a merge conflict since they change the same line on different branches, a merge from `v1.3.1` to `main` was done for you to address the conflict.

When you prepare a release, the idea is to create a stabilizing branch for you where you can prepare to actually ship, and immediately repurpose main for the *next* release's development.
