### ISSUE TITLE
[Question] Purely linear commits

### ISSUE THREAD

**Issue by virzak** [dotnet/Nerdbank.GitVersioning#564]
Is it possible to use GitVersioning to maintain a linear history.

Here is an example of a large project that does that. https://github.com/vercel/next.js
Releases which are frequent would result in a single commit instead of 3 commits and a new branch for every release.

**Comment by AArnott** [comment]
Of course, yes linear history is fine. NB.GV will just increment like always.

Perhaps your question comes from the behavior of the `nbgv prepare-release` command, since you mention 3 commits and a new branch. But that's just a tool to make a common versioning strategy easier. It is somewhat customizable but it doesn't work the way you want it to, you're very welcome to change the version.json file yourself in one commit.

**Comment by rcdailey** [comment]
> NB.GV will just increment like always

Could you clarify this please? My understanding is that the only time NBGV will "increment" the number (e.g. `1.0` -> `1.1`) is when you do `nbgv prepare-release`, it will increment the minor component (by default) on `master`. But I don't recall a way to do this without going through that command.

For example I think what we need is a `nbgv increment-version` that does that in-place.

**Comment by AArnott** [comment]
If the `version.json` file contains `1.2`, the first commit will be versioned `1.2.1`. The next commit will be automatically incremented to `1.2.2`, and so on. This is what I mean by incrementing.

To increment a version number specified in the `version.json` file, just change that file and commit the change. `nbgv prepare-release` works no magic. All it does it change that file (and optionally creates a servicing branch for the prior version). It's nothing you can't easily do manually.

**Comment by rcdailey** [comment]
I think there's an important distinction here. `prepare-release` will automatically increment the minor component. So in your example, it will see `1.2` and bump it to `1.3`. However, I can't do this without creating a release branch. My only alternative is `set-version` which requires me to remember the last number and manually specify `1.3`.

A useful use case for this is pipeline automation. I have a particular pipeline where I want to increment the minor version *after* I merge the release branch. It would be much easier if I had an `increment-version` option that did the same version incrementing that `prepare-release` does.

I think the gist of the problem is that `prepare-release` bundles too much functionality into one command. I would prefer that it be built on top of various other "plumbing" commands that allows users to separately utilize different tasks that `prepare-release` performs.

It's a bit off topic at this point, but that's my feeling on the version incrementing behavior. Might be worth to open a different issue for this.

**Comment by AArnott** [comment]
@rcdailey Have you read through [the docs on the prepare-release command](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md#preparing-a-release)? There are customizations to its behavior you can make in version.json to fit several workflows. If you don't want it to create a branch, I *suspect* you can achieve that.

**Comment by rcdailey** [comment]
I have read over it numerous times. The only thing close to what I'm talking about that it says it will do is, if you run the command on the release branch itself, it will modify the prerelease as needed, but it does not indicate that it will increment the minor version number. That happens on `master` and the purpose of running it on the release branch is to avoid doing the stuff on `master`, as I understand it.

This doesn't quite fit in with what I'm talking about.

**Comment by AArnott** [comment]
What I'm thinking of for you is a version.json file that looks similar to this:

```json
{
  "version": "1.0",
  "release": {
    "branchName" : "master",
    "versionIncrement" : "minor",
  }
}
```

With this committed, I think running `nbgv prepare-release` on your `master` branch will increment the minor version number only, which sounds like what you wanted. If that's correct, can you try that?

**Comment by AArnott** [comment]
If this doesn't work, we can consider adding a command to just increment the version. But I wonder why it's useful to automate this. For most folks, a version bump to this file is an infrequent, significant milestone that a human usually executes rather than one in some repeated, automated flow.

**Comment by rcdailey** [comment]
Sadly it doesn't work, it violates the schema:

![image](https://user-images.githubusercontent.com/1768054/114751849-49a28e80-9d1b-11eb-9c3f-9150194083fb.png)

And when I run it anyway I get this error:

```
$ nbgv prepare-release
Invalid 'branchName' setting 'master'. Missing version placeholder '{version}'.
```

I think the driver for this relates back to our discussion in the "release best practices" issue. There's a few limitations in Github Actions that force me to manage my release process a certain way. But ignoring that, the process itself isn't terrible or unreasonable. I'll dump all the dirty details below. Most of this is off topic, but I think it's beneficial to mention it here as it may be that my process and thinking can change so that the tool doesn't need to. I apologize in advance that this is yet again taking us further away from the original topic. Happy to delete this & move it to another issue if you feel that would be best.

Prior to and independent of making a new release:
- As I'm working on `master`, implementing features, update release notes in `CHANGELOG.md`

When I'm ready to release:
- Run a manual workflow to draft a new release, which:
  - Creates a new branch `release/1.0` (if we assume the current version is `1.0-alpha` on `master`)
  - Updates the `CHANGELOG.md` according to keepachangelog.com rules. Commit the changes.
  - Open a pull request to merge `release/1.0` into `master`
- Manually merge the pull request when ready, which:
  - Kicks off a build for the new merge commit on master
  - Product is built and artifacts are zipped
  - Snip the release notes from `CHANGELOG.md` for the immediate release
  - Create a Github Release with the zipped artifacts and the snipped release notes
  - Run `nbgv increment-version` to go from `1.0` -> `1.1`. Commit and push.

Regarding the version increment, there are a few different ways to go about it. I've also considered just incrementing the version directly on master *prior* to doing the release, as opposed to after it, but by doing it *after* and *inside the pipeline*, it's one less manual step I have to worry about. I've managed to boil down the release process to just two manual steps:

1. Start a manual workflow to draft a release
2. Merge a pull request to finalize the release

I prefer to eliminate step 2, and that may be possible, but I haven't gotten that far in my testing/research yet. For example I would want to see if I can either:
- Initiate the PR merge as the last step in the "draft release" workflow, which chain-triggers the build workflow after the merge
- Eliminate the PR completely, and just merge & push the branch on `master` to kick off another build. The condition I use for the "release" step in the build workflow would need to be thought out; I wanted to avoid having to rely on parsing commit messages or something. And there's not a "push" event type for merges where I can check the branch name (branch is not even guaranteed to exist after a merge).

There are some limitations that force this release model:
- Artifacts are not sharable between workflows. So the "build" workflow is actually two parts: Build and then Release. But the Release step is conditional on whether or not it was a pull request merge for a `release` branch. This is the biggest limitation as it means I can only ship the build that actively just finished in the same workflow.
- I cannot label any arbitrary build on master to be shipped. So we ship the tip commit on master at any given point. I could probably set up the "draft release" workflow to accept a SHA1 as input to control where I create the `release` branch from.
- I trigger my "Build and release" workflow on any push or pull request. If I wanted to release a build on the `release` branch itself, for example, I'm not sure how I would trigger that. I'd basically need some way to signal that the release branch is "done" while it is also being built. For example, I could trigger based on the PR merge event and just tag the release `HEAD^2`, but remember I can't access those artifacts anymore since I'm no longer doing it from within the build workflow itself.

As a side note, if you're wondering why I'm not using Azure Pipelines, it's because they apparently do not allow any parallel builds (I need to build my product as a matrix since I support multiple platforms). There's a process to email Microsoft to request a free tier for this, but it is a lengthy and unreliable process. So I decided to stick with Github Actions and see if I can make it work.

All of this is a long way of saying that making `nbgv` more flexible is only more helpful in these situations where I'm arguably dealing in edge cases (but a more accurate description is that `nbgv` would just be supporting less rigid delivery semantics).
