### ISSUE TITLE
nbgv not working after splitting subdirectory into different repo using `git subtree split`

### ISSUE THREAD

**Issue by rcdailey** [dotnet/Nerdbank.GitVersioning#579]
I used `git subtree split` to split a subdirectory, which had its own `version.json` that inherited from a parent, into its own repo.

When I opened my solution in the new repo, I get errors like:

```
System.InvalidOperationException: "version.json" inherits from a parent directory version.json file but none exists.
```

I deleted my `version.json` and did `nbgv install` to try to "start over", but I still get this error even though `inherit` property is no longer present in the `version.json`. I also now get errors like this:

```
System.InvalidOperationException: Unable to get version from commit: 245b8b72bb95218f0867740bbb39e384aec9f9b8
```

I think the way that the git history got spliced is causing a lot of confusion with NBGV. How can I reset/fix this?

**Comment by AArnott** [comment]
If the `version.json` file in the subdir had `inherit: true` in it when it become a root version.json file, that's invalid and you'll have to fix it, as you've already attempted to do. But since NB.GV walks history in order to calculate the version height, you can't just author a fixing commit because the past commit with the bad state will still be encountered. 

See https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/migrating.md for tips on how to recover and let me know how it goes.

**Comment by rcdailey** [comment]
Big part of this was not having a full understanding of how nbgv utilizes git history. Thanks to your explanation, I realized the obvious choice... I just did `git rebase -i --root` and added my `version.json` to the very first commit in whatever form I liked. Since it's a new repo, I am free to rewrite history as I'd like to "get things right".

Thank you for your help!
