### ISSUE TITLE
Best practice for automating github releases

### ISSUE THREAD

**Issue by rcdailey** [dotnet/Nerdbank.GitVersioning#585]
Hello,

I am building a .NET Core 5 command line application. I am running my build automation in Github Actions. Right now, I have a "test" job that builds and runs tests. After that, a matrix build takes place: A job spawns per platform I support to set up NBGV, build for a particular runtime (single executable) and upload that executable as an artifact. When my whole build is done, I get 3 executable artifacts (windows, mac, linux).

I've been really stumped on how to set up my release pipeline. Ideally when I trigger a release, the following happens:

- auto generate changelogs (maybe using conventional commits?)
- create a (draft?) Github Release with the generated changelogs + all 3 artifacts 

I'm not sure how to best trigger such a release process. Most I see rely on tags being pushed, but I don't see a reason to use tags when the versioning is being maintained by the pipeline anyway. Other than the major and minor components, I don't know what the version number will be, so I can't really create a tag locally and push it and use that to trigger a release.

Somehow I will need another way to signal to my build process to create a release. And assuming once I even figure that out, I need to find the right github actions to do it (there are many available, it's difficult to know which is best).

I realize this is likely off topic since it doesn't deal directly with NBGV, but I don't know where else to ask for advice. I want to continue using NBGV and I was hoping there are some techniques worth learning here.

**Comment by AArnott** [comment]
> Other than the major and minor components, I don't know what the version number will be, so I can't really create a tag locally and push it and use that to trigger a release.

You could use `nbgv tag` locally to create the tag and push it. Tagging releases is a very good idea, since `v1.2.3` is sometimes ambiguous to `nbgv get-commits` when history has multiple commits with that version and height, but a tag will always make it easy. When it is ambiguous, you can always find the commit ID in the built binary though since NB.GV stamps that in too.

As for the best way to trigger releases, in my experience, GitHub Actions are lousy for this workflow since there is no way to manually trigger a workflow. I use Azure Pipelines (also free) with my GitHub repos, which offers much more functionality including manual triggers. Although my favorite approach is a release workflow triggered by tagging an in-progress or completed build pipeline with `auto-release` and walking away. You can look at most of my more maintained repos for a `release.yml` file to see how I do this.

**Comment by rcdailey** [comment]
Thanks for your feedback.

You are incorrect that manual workflows are not possible in Github Actions. That functionality is [documented here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow). Maybe this is a newer addition that wasn't around when you researched it, I am not sure. I am still relatively new to Actions myself.

I will take a look at your repos and see if I can learn anything. Do you have a link to those repos I can use?

So far, I've seen a two-part workflow that seems nice. It basically would be:

1. Draft a release (manual trigger)
   1. Run `nbgv prepare-release`
   1. Run script to update changelogs, commit
   1. Open a pull request to merge `release/v1.0` to `master`
1. Publish release (triggered by the PR merge from last step)
   1. Tag build
   2. Create a Github Release, attach binaries and release notes

The idea itself sounds good, but there are a few details I'm unsure of. Namely, do you tag before or after merging the `release` branch. Ideally, all tags should be directly on `master`, but in practice that seems difficult to do, I think. Would be curious how your pipeline handles "where to tag".

**Comment by AArnott** [comment]
> You are incorrect that manual workflows are not possible in Github Actions. That functionality is documented here. Maybe this is a newer addition that wasn't around when you researched it.

Ya, I meant to add "last I checked", as this is decidedly new. 

My next question would be whether GHA has filled in the hole where a workflow may be triggered to consume artifacts from some particular run of another workflow. In essence, allowing a "release" workflow to consume a particular prior run of a "build" workflow. 

>  Do you have a link to those repos I can use?

I keep the latest and greatest patterns in my Library.Template repo. The release pipeline is [here](https://github.com/AArnott/Library.Template/blob/main/azure-pipelines/release.yml).

> Run script to update changelogs

I don't keep changelogs in source code, since they are already in git history and (in particular for me) GitHub issues and PR history. I use the GitHub Release task (as you'll see in my release pipeline) to automatically draft a GitHub Release with notes based on recent issues and PRs. It does a reasonably nice job with very little effort on my part.

> Ideally, all tags should be directly on master

Keep in mind that a tag applies to a commit, and a commit may belong to *n* branches, where *n* changes over time since branches can be created and destroyed over time for the same commit. I would rather say that I always release based on a build from a "public release branch" as specified in my version.json file. That typically means I release out of my default branch or a vX.Y branch.

But when I was talking about tagging earlier, I was referring not to git tags but Azure Pipeline tags, which I can apply to any run of a pipeline. When I tag with `auto-release`, the release pipeline will trigger, consuming the artifacts from the build pipeline to push to nuget.org and creating a github release. The github release knows the commit ID that the build pipeline was based on and when I publish the release, GitHub itself pushes the tag to my repo on the appropriate commit.

**Comment by rcdailey** [comment]
Sadly, it looks like (to your point) Github Actions is missing two key features:

* The ability to [download artifacts across different workflows](https://github.com/actions/download-artifact/issues/3)
* No ability to tag or label existing workflow runs

So I think I will abandon Github Actions for now. You mention you use Azure Pipelines. Any reason you choose this as opposed to something like Gitlab CI? Thanks a bunch for all the info so far.

**Comment by AArnott** [comment]
I don't know much about GitLab CI. I've used AppVeyor and a couple of others, and I find Azure Pipelines to be most capable and offer the most free resources.

**Comment by rcdailey** [comment]
Thank you for everything. I will close this out.
