### ISSUE TITLE
v3.4 regressed version height calculation involving path filters

### ISSUE THREAD

**Issue by marcominerva** [dotnet/Nerdbank.GitVersioning#587]
Hi!

I have a project with this _version.json_ file:

```
{
	"$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
	"version": "1.2",
	"publicReleaseRefSpec": [
		"^refs/heads/master$" // we release out of master
	],
	"nugetPackageVersion": {
		"semVer": 2
	},
	"pathFilters": [ "." ]
}
```

With this configuration, If I use Nerdbank.GitVersioning version 3.3.37, everything works like a charm. However, as soon as I update it to the v3.4.194, the git versioning isn't calculated anymore (it is always set to 0).

**Comment by AArnott** [comment]
Thanks for reporting. We have had a few regressions in 3.4 due to switching from libgit2 to our own managed git implementation. See our [release notes](https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.4.142-alpha) for how to switch 3.4 back to libgit2 as a potential workaround.

I haven't heard of the symptom you describe. Can you provide repro steps that we can use?

**Comment by marcominerva** [comment]
You can see the problem in this repository: https://github.com/marcominerva/TinyHelpers/tree/develop/src/TinyHelpers. Now the Nerdbank.GitVersioning is version 3.3.37, so when I build the project (that contains the _version.json_ file I shown you above), the version is correctly set to 1.2.xxx. If, instead, I update the version to v3.4.194 and just retry to rebuild the project, the version returns to the 1.2.0.

**Comment by AArnott** [comment]
Great. I can repro the problem. The workaround I linked you to is effective as well. I'll continue investigating.

**Comment by AArnott** [comment]
@qmfrederik this regression is apparently because some code was never converted for the managed git implementation around path filters support:

https://github.com/dotnet/Nerdbank.GitVersioning/blob/8126d95e2c789efb42f9a89cf576fe75e69119fc/src/NerdBank.GitVersioning/Managed/ManagedGitExtensions.cs#L197-L216

Do you recall why this wasn't done? Is it going to be something we can fill in?

**Comment by qmfrederik** [comment]
There's obviously a bug, but I _think_ the intent was that [`IsRelevantCommit`](https://github.com/dotnet/Nerdbank.GitVersioning/blob/8126d95e2c789efb42f9a89cf576fe75e69119fc/src/NerdBank.GitVersioning/Managed/ManagedGitExtensions.cs#L251-L317) replaces the code which was commented out.

Since you can reproduce the issue, can you share a unit test which reproduces the behavior?

**Comment by AArnott** [comment]
Yes, I'm working on writing a unit test now.

**Comment by AArnott** [comment]
Test added in the [fix587 branch](https://github.com/dotnet/Nerdbank.GitVersioning/compare/v3.4...fix587). It passes on libgit2 and fails on managed git. It only repros when the test uses a path filter _two_ folders deep in the tree (1 level deep did not cut it), and included a version bump. @qmfrederik do you have time to investigate?

![image](https://user-images.githubusercontent.com/3548/114430083-4a042380-9b7b-11eb-9227-00a7d2bf04d4.png)

**Comment by amin-sage** [comment]
@AArnott just wondering if this has been released already? Thanks.

**Comment by AArnott** [comment]
@amin-sage  It's available on our CI feed here: https://dev.azure.com/andrewarnott/OSS/_packaging?_a=package&feed=PublicCI&package=Nerdbank.GitVersioning&protocolType=NuGet&version=3.4.205&view=overview

Can you test it and give us the thumbs up that it's effective before we push to nuget.org?

**Comment by tg73** [comment]
I just got hit by this issue - I didn't notice straight away and it was very confusing when I started seeing height 0 (height zero) on builds that were previously "sensible" (given that height should never be less than 1 unless using offset). I can confirm that 3.4.205 from the CI feed gives sensible height. Thanks @qmfrederik for the fix!

**Comment by AArnott** [comment]
I'm pushing 3.4.205 to nuget.org now.

**Comment by amin-sage** [comment]
Works fine here as well, tested with 2 different projects, thanks.
