### ISSUE TITLE
Feature request: MSBuild property to drive generation of `GitCommitDate` field

### ISSUE THREAD

**Issue by alexrp** [dotnet/Nerdbank.GitVersioning#639]
I'm working on a custom .NET runtime where the API surface does not (currently) include `System.DateTime` and `System.DateTimeKind`. The generation of the `GitCommitDate` field is therefore a bit problematic.

It would be great if my runtime's MSBuild SDK could set some property such as `GitCommitDateFormat=Unix`. This could cause it to be emitted as `internal const long GitCommitDateUnix = <result of new DateTimeOffset(new DateTime(ticks)).ToUnixMilliseconds()>;` or something along those lines.

**Comment by AArnott** [comment]
Do you actually need the property, or would adding an option to suppress it be adequate for you?

**Comment by alexrp** [comment]
I can't think of any uses for the property off the top of my head, so suppressing it is *probably* fine. The above was just a suggestion in case suppressing it entirely would be an undesirable feature to support.

**Comment by AArnott** [comment]
I'd take a PR that adds an msbuild property that suppresses all `DateTime` properties. Or even better, find an msbuild property that already exists that indicates that the target .NET runtime is yours and pass that into the msbuild task so that it can automatically suppress this and any future properties that are incompatible with your runtime.

**Comment by alexrp** [comment]
Closing this since I've put this experiment on ice for now. Will reopen if I revisit it at some point.
