### ISSUE TITLE
CI trigger issues following prepare release

### ISSUE THREAD

**Issue by dariusonsched** [dotnet/Nerdbank.GitVersioning#681]
Andrew/others - Thanks in advance for your time.

Running into an issue using `nbgv prepare-release` and the triggering (or lack thereof) of our release pipeline's CI trigger.

We have an Azure DevOps YAML pipeline that rules it all (Build, Dev, Stage, Prod) with a separate "prepare release" YAML pipeline that does the following:

1. Pulls down the GitHub repo
2. Checks out the 'develop' (default) branch
3. Creates and checks-out a 'versioning/<current-beta-version>'
4. Installs NBGV
5. Runs `nbgv prepare-release`
6. Pushes both the 'releases/v#.#' and 'versioning/<current-beta-version>' branches to origin
7. Creates a PR from 'versioning/<current-beta-version>' into 'develop' (default)

What is wrong is our primary YAML pipeline is not seeing the commit on 'releases/v#.#' probably because the branch doesn't exist at origin until it gets pushed with the commit already intact.

Would `nbgv prepare-release` work with an existing releases branch if we:

1. First create a 'releases/v#.#' branch on the build agent
2. Push this branch to origin
3. Switch to the 'versioning/<current-beta-version>' branch
4. Run `nbgv prepare-release`
5. Push both branches to origin

The nbgv documentation states if prepare-release is run on an existing branch, it doesn't create a new branch, but I'm concerned it will just prepare that branch for release without versioning what was in develop(?)

Thank you for your thoughts.

**Comment by AArnott** [comment]
Are you saying that your yaml file includes a branch trigger that includes `releases/v*` as a pattern, and that it doesn't cause your pipeline to run when a *new* branch is pushed? Does it trigger when you push a commit subsequently on that same branch?

`nbgv prepare-release` will fail if you try running it when the branch it would create already exists *locally*. If AzP will trigger CI on a push to an existing branch but not a new one, you could perhaps make it work using your proposed workaround, but inserting a step after step 2:

2.5. `git branch -d releases/v#.#`

This will delete the *local* branch (after you pushed it to `origin`), allowing `nbgv prepare-release` to "create" it. Then when you later push the "new" branch again, `origin` will be happy to accept it because it is a fast forward of what you pushed before.

**Comment by dariusonsched** [comment]
Andrew, you are correct.  a new `releases/*` branch (set as a CI trigger in YAML) being pushed does not trigger a build in AzP, but a push does.

Love your idea - to push the branch up, then delete the local copy before running `nbgv prepare-release`.  Will give that a go. Thanks!
