### ISSUE TITLE
`nbgv prepare-release` puts git in bad state (when LFS is in use)

### ISSUE THREAD

**Issue by vchirikov** [dotnet/Nerdbank.GitVersioning#685]
Hi, I have a repo with lfs and `dotnet nbgv prepare-release` breaks .git in the repo. I think it can be caused by the managed git implementation + lfs. After `prepare-release` .git is broken and I can't reset / checkout another branch or do something with git. After the command `.git/index.lock` is presented, but if I it delete it won't help.

![image](https://user-images.githubusercontent.com/40987940/140894795-62a67fcd-87a5-4ed6-8b0f-5bc0ebd7caae.png)

p.s.
```
git st == git status
git lg == git log
git go == git switch
```

cc: @AArnott

**Comment by vchirikov** [comment]
It's the same with env `NBGV_GitEngine=LibGit2`, so it doesn't work at all :(

**Comment by AArnott** [comment]
`nbgv prepare-release` doesn't use the managed git implementation since that is read-only and `prepare-release` creates commits, branches, etc. So this may be a big in libgit2 or libgit2csharp.

> After the command .git/index.lock is presented, but if I it delete it won't help

What does that mean? `index.lock` is a file, not a command. What do you mean by it being presented? 
Do you mean that file is left behind by `nbgv prepare-release` and deleting it doesn't resolve the problem?

Given your symptom is that switching branches doesn't work but you cut out the screen clip that includes whatever error message it showed, I feel like my hands are a bit tied to help you.

**Comment by vchirikov** [comment]
> Do you mean that file is left behind by nbgv prepare-release and deleting it doesn't resolve the problem?

Exactly

> but you cut out the screen clip that includes whatever error message

this was without blur, just nothing happened.
Let me show

![image](https://user-images.githubusercontent.com/40987940/141115064-91d1595e-6d65-4d55-be79-5391961cdd58.png)


So git commands like `checkout`, `switch`, just didn't do anything, there were no errors.

But `git gc` shows:
```
git gc
fatal: failed to run repack
```

That's all.

**Comment by AArnott** [comment]
Thanks. I'll try to repro with my one repo that uses LFS.

**Comment by vchirikov** [comment]
It's still reproducible with the latest git `git version 2.34.0.windows.1`

**Comment by AArnott** [comment]
I only have one LFS repo, and your bug didn't repro on it. Can you share a public git repo that demonstrates the problem?
Alternatively, you might ask the libgit2sharp folks, since this is almost certainly a bug on their end.

**Comment by vchirikov** [comment]
It's on a private repository, interesting that my colleagues can't repro this. So maybe something wrong with my PC. I'll check this, thanks anyway.

**Comment by vchirikov** [comment]
Can't reproduce in another repo. Anyway it looks like libgit2sharp issue. Closed for now.
