### ISSUE TITLE
Feature request: Increment version once if several commits were committed with "rebase and merge"

### ISSUE THREAD

**Issue by imsh** [dotnet/Nerdbank.GitVersioning#720]
Imagine that the current version of some branch is 1.0.100 and then someone merges a PR with 3 commits using "rebase and merge" merge (semi-linear in azure devops terms). 
Right now, the new commit will get version 1.0.104 as there are 3 new meaningful commits + 1 merge commit. 
What I would like is an option so that merge commit's version evaluates to 1.0.101. 
This way, any CI builds will have nice increments in version numbering without jumps and gaps and with smaller overall numbers.

The current "alternative" way to get nice versioning is to just squash all the changes into one commit instead of doing "rebase and merge", but that approach destroys the history of the commits - not optimal as well.

**Comment by KalleOlaviNiemitalo** [comment]
Would this be like `git rev-list --first-parent | wc -l`, or something that does not depend on the order of parents?

**Comment by AArnott** [comment]
The algorithm for counting version height has always been based on the number of commits along the longest path to where the version in version.json was last changed. This ensured that versions would never go backwards. I want to be cautious about even adding an option that would follow only first parents in calculating versions, thinking through the various cases to make sure they never go backwards. 

If someone could direct push a merge commit where the parents are reversed, they could make the version height go backwards for example. Now, if you have branch policies set such that no one is allowed to directly push, then that should theoretically never happen. 

I don't think I have anything against this proposed option, but I'll just venture to say that 'jumps and gaps' in your CI build history is a natural part of being based on git history, and your releases certainly won't be just +1 from the prior release (unless you override defaults), so NB.GV users tend to just accept that versions aren't always +1 from what they had last time.

**Comment by sfwester** [comment]
> so NB.GV users tend to just accept that versions aren't always +1 from what they had last time.

We are just looking into NB.GV and these jumps are making it hard to make sure our changelog aligns with the versions that get produced.

Is there a changelog process that NB.GV users generally leverage to alleviate this?

**Comment by AArnott** [comment]
@sfwester This may not be what you're looking for, but my changelog process is simply this at release time:

![image](https://user-images.githubusercontent.com/3548/217001479-d10733d0-ee0b-48ad-980b-c89e9f02f39b.png)

Well, that and having well-named PRs so that the above process produces something good. Not only does this save a lot of trouble mid-release, it works across arbitrary versions, including servicing releases.

Alternatively, if you're checking in a changelog file with each change, perhaps have a section for the 'next release' without naming it until you're about to release it. At that point, the version is more predictable. I won't say perfectly predictable though, if you want to specify the version precisely, because there are plenty of releases that I've seen get reset at the last minute when a bug is found and another commit (and thus another bump in the git height) changes the computed version. I try to avoid any requirement for committed source code to predict what a released version will be.
