### ISSUE TITLE
Unexpected behaviour after git move/rename version.json to root

### ISSUE THREAD

**Issue by Nazardo** [dotnet/Nerdbank.GitVersioning#734]
Hi @AArnott,

first of all, I would like to thank you for this beautiful project/module that brings consistent and reliable versioning to all our software.

I stumbled upon a strange behaviour after, due to repository changes, I had to move my `version.json` from a subdirectory to a parent directory. [This test repository](https://github.com/Nazardo/test-issue-nbgv) replicates the problem in a simpler scenario.

At the beginning of the repository history, only one folder was expected to contain code, so `version.json` was placed in such folder (folder `b` in the example). In a later stage, things evolved and at least two folders now contain code that should be versioned, and with consistent version numbers (folders `b` and `c` in the example).

I moved `version.json` to the root and used the `"versionHeightOffset": N` to obtain the correct version number when invoking `nbgv get-version` from the root folder (see HEAD commit). `"pathFilters"` have been set up to consider only folders `b` and `c`.

After some time we noticed that the output of `nbgv get-version` is different when executed in the root folder, and when executed in `b` or `c`.

```
[~/repo] nbgv get-version
Version:                      1.0.4.26704
AssemblyVersion:              1.0.0.0
AssemblyInformationalVersion: 1.0.4-beta+50687065f1
[~/repo] cd b
[~/repo/b] nbgv get-version
Version:                      1.0.7.26704
AssemblyVersion:              1.0.0.0
AssemblyInformationalVersion: 1.0.7-beta+50687065f1
[~/repo/b] cd ../c
[~/repo/c] nbgv get-version
Version:                      1.0.4.26704
AssemblyVersion:              1.0.0.0
AssemblyInformationalVersion: 1.0.4-beta+50687065f1
```

In folder `b` the version number is not the one I expect. Assemblies built from folder `b` have an assembly version greater than expected.

My understanding is that this is caused by how the _rename_ operation on `version.json` is parsed. On a separate branch, I have split the _move_ into two separate commits, one that deletes `b/version.json` and one that adds the new `version.json` in the root. In this branch, version numbers are ok.
Unfortunately, it took some months for me to discover these inconsistent assembly versions, so I am no longer in a position to easily rewrite git history and split the commit with the _move_.

Is this a bug? Thanks if you have time to look into it.

**Comment by AArnott** [comment]
This is by design. *You* took very special care to use `versionHeightOffset` to avoid regressing your version number, which is laudable. But NB.GV doesn't rely on that to make sure it never accidentally regresses the version number. It isn't really about you _renaming_ the version.json file either.
What's going on here is that version calculation happens on a per-project directory basis by default. Your `b` project was already building as 1.0.3 when version.json was in its directory. Then a commit later, it would have been 1.0.4, except that the version.json file now added 3 to the `versionHeightOffset`, so it added 3 more and produced 1.0.7.
On project `c` (and the repo root), it was never versioned before (because no version.json applied) so its default height calculation started at 1.0.1, and `versionHeightOffset` added 3 making it 1.0.4.

The invariant that's being enforced here is that no project ever goes backwards.

To achieve your goal of all projects being 1.0.4, you have a few options:

1. Bump your root-level version.json file from `1.0` to `1.1`. This change to the specified version number resets the height calculation, putting all projects underneath it at 1.
1. Apply [the build optimization](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/msbuild.md#reducing-getbuildversion-invocations) that forces NB.GV to only calculate the version once for the entire repo. Thus, project `b` and `c` will use the same root-level version.json file instead of b looking for a `version.json` file in its own directory as it walks history.
1. The nuclear option: Commit a total removal of `version.json` and commit its re-introduction. NB.GV walks history up until no version.json is found and then stops. So having a commit without one will cut off the version height calculation, allowing you a fresh start. Note that you cannot *merge* or *squash* these commits into your main branch. Merging would offer NB.GV a path where version.json was never missing. Squashing would combine your delete and add commits, leaving no commit where the file was missing. So this approach requires that you do a direct push of both commits to your main branch. 
1. You could also drop a new version.json file in `b` to customize its own versionHeightOffset, but this can be tricky to pick just the right number and then you have two files to maintain instead of one till you bump the version and hopefully remember to delete the extra version.json in the same commit. So I don't recommend this option.

**Comment by Nazardo** [comment]
Thank you very much for the thorough explanation. 🙏
I had not thought about option 1! 😄 As soon as we will increase the version number to _prepare_ for our next release, everything will indeed be coherent again. In the meantime, we will handle things with a small change in our CI pipeline.

Have a good day!
