### ISSUE TITLE
AssemblyVersion not being changed

### ISSUE THREAD

**Issue by OFark** [dotnet/Nerdbank.GitVersioning#775]
So I have installed nbgv via the CLI tool, and created a version.json and committed it. 
Everything about the built assembly is changed apart from the AssemblyVersion. 

So I've added the section from the version.json example:
```
"assemblyVersion": {
    "version": "x.y", // optional. Use when x.y for AssemblyVersionAttribute differs from the default version property.
    "precision": "revision" // optional. Use when you want a more precise assembly version than the default major.minor.
  },
```

replacing "x.y" with "1.0" and nothing changes. However, Visual Studio is complaining that this node doesn't match the schema
![image](https://user-images.githubusercontent.com/4558132/172627222-c8840cfa-2143-412a-8c3d-b8451c0c63af.png)
So I noticed that the assemblyVersion (according to the schema can just be the version semver so I set it to:
`"assemblyVersion": "1.0",`
Still nothing, so I set it to "2.0" and low and behold my AssemblyVersion changes from 1.0.0.0 to 2.0.0.0, shouldn't it be injecting some Git version values in here? Or have I missed a trick?

**Comment by AArnott** [comment]
The schema should validate. If VS is complaining that it doesn't, find out why and fix that and I suspect NB.GV will be happy after that and do more of what you expect.
Also: version.json must be valid in every commit. If a prior commit in your git history has an invalid version.json file, that could be your problem. Check out [this doc](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/migrating.md) for instructions on how to sanitize your history of an invalid file (or just roll back history to when you started and try again).

**Comment by OFark** [comment]
That screenshot is all I get regarding the schema validation, "Property name is not allowed by the schema at" for the code from the example.
Yes, I had experience with the version.json file being incorrect in the commit history, and for some reason, nbgv was using that, I had to remove it from the repository and start again. 
But to my point about the AssemblyVersion, shouldn't it be adding version information to that?

**Comment by OFark** [comment]
Ok so I've tried removing the version property from the assemblyVersion node and that's sorted it all out. Should that be there in the version.json example?

**Comment by AArnott** [comment]
Ah, ok I see what's happening now. Thank you for that additional detail. As [the schema indicates](https://github.com/dotnet/Nerdbank.GitVersioning/blob/a39b14e9cd5b2cbaf88fa5e3ae8468392d846308/src/NerdBank.GitVersioning/version.schema.json#L41-L65), you are not allowed to provide _both_ an assembly version _and_ specify its precision. If you want high precision on your assembly version, it must be based on the ordinary `version` property, which is why you're seeing it based on `1.0`. Or when you specify `2.0` explicitly, NB.GV goes into the mode of ignoring `precision`, since per the schema that property is not expected.

Do you have a requirement that assembly version differ from your other versions, yet still have a 3rd and/or 4th component that's calculated from the rest of the git version computation?

**Comment by OFark** [comment]
No, actually I didn't need to change the assembly version, just the precision. Not having much experience with JSON schemas I've learnt something today. Thanks. It's kinda obvious really when you realise it's called **One**Of
