### ISSUE TITLE
Question:  Recovery from a bad version.json commit

### ISSUE THREAD

**Issue by spowser** [dotnet/Nerdbank.GitVersioning#815]
We found a situation where we wanted to get some guidance on what the best path forward would be.

Issue:  We have an invalid version.json file in the commit history a couple days back.  This should never happen, but Murphy's Law reared its head

```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",	  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
<<<<<<< Updated upstream
  "version": "1.6",	  "version": "1.6",
=======
  "version": "1.5",
>>>>>>> Stashed changes
  "publicReleaseRefSpec": [	  "publicReleaseRefSpec": [
    "^refs/heads/main$"	    "^refs/heads/main$"
  ],	  ],
  "pathFilters": [	  "pathFilters": [
    "./",	    "./",
    "../Project.Name"	    "../Project.Name"
  ]	  ]
}	}
```

Would incrementing the version to 2.0 simply prevent needing to walk the commit history to this malformed file?  Is there a better way to resolve this?  Rewriting the git history is unfortunately not an option.

**Comment by AArnott** [comment]
Ya, this happens. :)

Check out [the migrating doc](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/migrating.md) as it describes how to recover. Both sections will be useful to you, since after the 'clean break' commits your version height will be reset so you'll have to artificially inflate the number as documented to get back to where you want to be.

**Comment by akitson-degreed** [comment]
hi @AArnott .  I am working with @spowser on this issue and we are stumped.
We have followed the instructions in the migrating doc like so.
1. Removed all version.json files in the entire repo.  Commit directly to main.
2. Re-add the version.json files.. increment the major version number to the next unused major version (just to be safe).  Commit directly to main.

After this, everything seems to work.. for a bit.  Then, within 1 or 2 days, our automated builds start failing in both GitHub Actions and Azure Pipelines.  We've checked our checkout steps on all the builds to ensure they are doing a deep clone.

Based on the error, it seems that it is still attempting to read a previous commit of a bad version.json.

I think the issue is that we are recreating the version.json file in the same location.  We aren't moving the file, we are recreating it in the same location, with correct schema.

Any ideas?  Is there a way to force the tool to only start walking the history from a particular commit?

**Comment by AArnott** [comment]
> I think the issue is that we are recreating the version.json file in the same location

No, that's not it.

Given it reoccurs within a day or two, I'd say the problem is that you are pushing more commits to main with *merges* that skip past your scrubbing of history. If any path in history from HEAD exists where version.json was *not* deleted, then NB.GV will keep discovering the faulty one. I'm not sure the migration doc calls out this risk, but after fixing it (again) by breaking the connection per the doc, you'll have to rebase all your outstanding topic branches to the tip of your default branch, so that when they merge they won't recreate a path to the prior commits. Or you could *squash* all your topic branches instead of merging them.
