### ISSUE TITLE
Question: Best/any way to implement git versioning with a shallow git fetch

### ISSUE THREAD

**Issue by DutchBlackOp** [dotnet/Nerdbank.GitVersioning#846]
We are currently using Nerdbank Gitversioning for our versioning inside our build pipelines.
Azure DevOps and other devops environments are going towards shallow git fetch on default for build agents.
And we are also having issues with doing a full clone every time (escpecially for big projects), so we would also like to make use of a shallow git fetch.

Do you have any advise on how to use shallow git fetch while still using git versioning?

**Comment by AArnott** [comment]
You could shallow fetch, with the depth set to some non-zero number that's large enough to reach to the last time you released. That would be enough for NB.GV to work. 

To get NB.GV to work with fethDepth: 1 would require looking up git history via the REST API instead of local git history. Given the number of HTTPS calls required, that would take _much_ longer than a local git clone would, and would likely get your builds failing due to throttled REST calls.

There simply is no substitute for git history in a git history based version computation.

Personally, I'll be continuing to set my pipelines for deep clones. I don't care that their defaults are for shallow clones. It's a default that I need to change, is all.
