### ISSUE TITLE
Vulnerability in NuGet dependencies

### ISSUE THREAD

**Issue by michael92** [dotnet/Nerdbank.GitVersioning#849]
Hi,

NBGV tool is using `NuGet.PackageManagement`:
```
<PackageReference Include="NuGet.PackageManagement" Version="5.11.0" />
```
This package relies on `NuGet.Commands`, which has known vulnerability CVE-2022-41032.

According to this issue https://github.com/NuGet/Home/issues/12149:
> Any NuGet.exe, NuGet.Commands, NuGet.CommandLine, NuGet.Protocol 5.11.2 version or earlier.

are affected.

Are you planning to release a new version with a patch in the near future?

**Comment by michael92** [comment]
When we have a package reference to the `Nerdbank.GitVersioning` in any project, we still are getting alerts from Mend (formerly WhiteSource).

**Comment by AArnott** [comment]
Wow. That's pretty weird that Mend would flag Nerdbank.GitVersioning when it _doesn't_ depend on NuGet.PackageManagement, just because another project (nbgv) in the same repo depends on it.

And I highly doubt this is exploitable in a client program like nbgv, but I haven't researched it deeply. 

Since you're impacted by it though, I'll try to upgrade.

**Comment by AArnott** [comment]
Thanks for that research. Linux is an interesting use case. The fix to nbgv is already up on nuget.org.
