### ISSUE TITLE
What Is The Proper Workflow?

### ISSUE THREAD

**Issue by shawnallen85** [dotnet/Nerdbank.GitVersioning#884]
Howdy,

What is the proper git workflow for using NBGV?

I've been doing the following:

main branch
 + dev branches (squash to main when done) (dev/{feature})
 + release branches (release/v{N.M}, etc.)
    + dev branches (squash to the release branch)

But in doing that, the versioning got wonky, if that makes sense.

I would have things that go from 1.0.1 to 1.1.2 (rather than say 1.1.0).

Thanks,
Shawn

**Comment by AArnott** [comment]
Squashing reduces the number of commits, so in a git history-based versioning system, squashing will make the version go backwards compared to the original source branch. For example, if main is at 1.0.31 and you create a topic branch from that, commit a few times and get 1.0.35, then when you squash back to main you'll get 1.0.32, which is greater than what main was, but less than your topic branch was. If that's an issue, merge instead of squash. 

You should never squash across long-lived branches (e.g. release branches and main). That's good git health in general as it avoids needless merge conflicts.

My personal flow is I do most work in `main` via topic branch, and I merge (or sometimes squash) my topic branches into main. I create servicing branches off of main as it stabilizes toward a release. I may use `nbgv prepare-release` for this. When my servicing branches need a fix, I prepare a topic branch based on a commit that `main` and that servicing branch have in common (`git merge-base v1.2 main` is great for revealing what this commit is, assuming v1.2 is the name of my servicing branch). Then I _merge_ my fix into my servicing branch as well as main (in either order) so that git history shows the fix is in both branches. Most of this isn't actually important for nb.gv purposes, but it's a flow I generally recommend when you ship client software. If you're shipping a cloud service where you have only one branch that ever matters, you can do that too.

Does that help?

> I would have things that go from 1.0.1 to 1.1.2 (rather than say 1.1.0).

With NB.GV, where versioning is based on commits, the default behavior is counting starts at the first commit as 1. So as soon as you bump version.json for version 1.1, that commit will actually be 1.1.1. If you _really_ want it to be 1.1.0, you can do that using the `versionHeightOffset` property in the version.json file by setting it to -1. But besides customers not _really_ caring whether your package is 1.1.0 or 1.1.1, it's also not practical to try for 1.1.0 in practice because so often you'll need follow-up commits before you build your first 1.1 release anyway, so in the end it will often be more than 1.1.0 or 1.1.1 anyway. And if you keep decrementing the `versionHeightOffset` to 'regain' 1.1.0, you're very much defeating one of the major outcomes of git-based versioning which is that you never build the same versioned package from more than one commit. A cardinal rule with packaging is that each version is unique, so you never want to go backwards.

**Comment by shawnallen85** [comment]
I think this does help -- thanks for the details, I appreciate it!
