### ISSUE TITLE
Versioning of VS imagemanifest files

### ISSUE THREAD

**Issue by josesimoes** [dotnet/Nerdbank.GitVersioning#887]
Hi,

I was trying to use the same approach as with vsixmanifest files and use `|%CurrentProject%;GetBuildVersion|` in a imagemanifest in order to get the version in the resources declaration.

Like this: 
`<String Name="Resources" Value="/nanoFramework.Tools.VS2022.Extension;v|%CurrentProject%;GetBuildVersion|;c78be3280fbde583;Component/Resources" />`

Code file with the "fix" [here](https://github.com/nanoframework/nf-Visual-Studio-extension/blob/502b5e568340359749150d470bde1e3355c9dd93/VisualStudio.Extension-2022/NanoFrameworkMoniker.imagemanifest#L6).

This is because icons in .NET nanoFramework  VS2022 extension are randomly disappearing and this fix was suggested by VS team.
See issue in VS Developer Community [here](https://developercommunity.visualstudio.com/t/Extension-icons-missing-after-update/10242633?) and the proposed fix.

Any thoughts on this please?

cc @Newrad0603 @tinaschrepfer @ellerbach

**Comment by AArnott** [comment]
I don't have access to the feedback ticket, evidently.
If the syntax works (which would require that `imagemanifest` files process macros like this the same way `vsixmanifest` files do), then I'd say go for it. I just don't know imagemanifest files enough to say that it works. 

Why do imagemanifest files need the version? Is it an _assembly_ version that they need? If so, `GetBuildVersion` will not give that to you. It gives a more high-level (and usually more precise) version. If you need the assembly version, you'll have to author an msbuild target that depends on `GetBuildVersion` and then returns `$(AssemblyVersion)` as a target output, and then use that in your imagemanifest file instead in order to get reliably good results.

And what's the `c78be3280fbde583` hex string for?

**Comment by josesimoes** [comment]
I've wrongly pasted the URL to the VS Dev Community ticket. It's public.
https://developercommunity.visualstudio.com/t/Extension-icons-missing-after-update/10242633?

It seems that `imagemanifest` files aren't processed so this would work. I've tried the above and the GetBuildVersion placeholder is not replaced on build.

According to @Newrad0603 VS2022 has an improved way of loading assemblies which is causing us issues. 
The VS extension assembly was a signed one (it's not anymore since the last attempt to fix this) and the  `c78be3280fbde583` is (was) the private key for the strong signing.

**Comment by AArnott** [comment]
> the c78be3280fbde583 is (was) the private key for the strong signing

I suppose you mean the assembly public key token rather than the private key.

It's unfortunate that VS2022 requires an assembly full name to be hard-coded in a source file when it doesn't support macros. The approach you tried would have been elegant had it worked. 

Shall we close the discussion here?

**Comment by josesimoes** [comment]
> I suppose you mean the assembly public key token rather than the private key.

🤦🏻‍♂️ you are of course correct!! My bad typing on a rush and not thinking... 😁 
>

**Comment by josesimoes** [comment]
> And to be clear, it sounds like you resolved the issue by removing the strong name from your assembly, which evidently removes the need for the assembly version to be hard-coded. Is that right?

I did remove the strong name & signing from the VS extension assembly in order to "revert" to the simplified assembly naming convention on the `imagemanifest` file. Unfortunately that did fix the issue... There are still users that can see the icons after the update and others don't. 

But yes, as far as nbgv is concerned, there is no issue. 
Thanks for looking into this and for you work on this tool! 👍🏻  😃

**Comment by AArnott** [comment]
> Unfortunately that did fix the issue

I believe you meant "did *not* fix the issue". 😉

**Comment by josesimoes** [comment]
oh my... twice in a row... this is becoming embarrassing... 😊 🤪 🤣
